# Generated by Django 5.0.3 on 2024-04-21 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='User',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
