# Generated by Django 5.0.3 on 2024-04-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_imagecinco_product_imagecuatro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('MEMORIAS', 'ALMACENAMIENTO'), ('PROCESADORES', 'PROCESADORES'), ('GABINETES', 'GABINETES'), ('MOUSES', 'MOUSES'), ('VENTILADORES', 'VENTILADORES'), ('MONITORES', 'MONITORES'), ('TECLADOS', 'TECLADOS'), ('TARJETAS GRÁFICAS', 'TARJETAS GRÁFICAS'), ('TARJETAS MADRES', 'TARJETAS MADRES')], max_length=200, null=True),
        ),
    ]
