# Generated by Django 5.0.3 on 2024-04-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_product_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('MEMORIAS', 'MEMORIAS'), ('ALMACENAMIENTO', 'ALMACENAMIENTO'), ('PROCESADORES', 'PROCESADORES'), ('GABINETES', 'GABINETES'), ('MOUSES', 'MOUSES'), ('VENTILADORES', 'VENTILADORES'), ('MONITORES', 'MONITORES'), ('TECLADOS', 'TECLADOS'), ('TECLADOS GAMER', 'TECLADOS GAMER'), ('TARJETAS GRÁFICAS', 'TARJETAS GRÁFICAS'), ('TARJETAS MADRES', 'TARJETAS MADRES'), ('TARJETAS DE RED', 'TARJETAS DE RED')], max_length=200, null=True),
        ),
    ]
