# Generated by Django 5.0.3 on 2024-04-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_product_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qualitnueve',
            new_name='qualitynueve',
        ),
    ]
